### ISSUE TITLE
Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors

### ISSUE THREAD

**Issue by cshopping** [lshug/first-order-model-tf#11] opened 2021-04-15 11:27 UTC
we aiming to use the GPU support to improve inference time for our model in Android devices but the following error is raised,: 
 Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
 how can we mitigate this issue?
 thanks

**Comment by lshug** [comment] 2021-04-15 17:16
Hello.

It is a known limitation of TF Lite's GPU and NNAPI delegates that they cannot handle dynamically shaped tensors, i.e. tensors whose shapes are dependent on the input shape of the inputs. At several points in code I do manually get the batch dimension either through tf.shape or reduce_summing a tensor's int-casted ones_like on the batch axis. However, during tf lite conversion all of those should be converted to static 1s. There might be a dynamic shape slipping in during the conversion stage.

Alternatively, this error is also caused when control flow ops slip into the model, but as far as I'm aware, no control flows make it to the converted model. 

Can you try to separately run kp_detector, process_kp_driving, and generator using the GPU delegate and tell me which ones are throwing the error? That will narrow down some suspects.

In the worst case scenario, where we are unable to nail down the problematic tensor/op, I could add a build arg that would replace all batch size-inferring tensors with a static tf.cast(1, 'int32') during build. I'd rather avoid that, as it would require adding a special 'static_build' argument to my custom keras layers that would not be orthogonal to the usual style and best practices of keras layers. Let's try to find the culprits first.

**Comment by cshopping** [comment] 2021-04-16 03:43
hi, i try to  separately run kp_detector, process_kp_driving, and generator using the GPU delegate, all of them throw this error....

**Comment by lshug** [comment] 2021-04-16 04:41
Looks like there's no way around adding in that build arg. 

We'll have to do an experiment. I added a new feature branch [here](https://github.com/lshug/first-order-model-tf/tree/static_batch_size). Please pull from it and build the models with ```build.py --staticbatchsize 1```. This will replace tf.shape call in process_kp_driving with a static 1. If the problem is only caused by tf.shape (and the respective op FL::ShapeOp), then process_kp_driving will no longer throw the error, whereas kp_detector and generator still will. If that turns out to be the case then I'll add the same behavior to generator and kp_detector and we'll be able to call it a day. On the other hand, if the error persists in process_kp_driving even without tf.shape, then we'll have to investigate further.

While we're at it, I added some [notes](https://github.com/lshug/first-order-model-tf/blob/main/OPS.md) you might be interested in about replacing certain operations in the code with a series of other operations that are GPU delegate-compatible, so that tflite interpreter won't have to constantly jump back and forth between the CPU and the GPU, which is rather costly in terms of model latency, and might offset the performance gain from using the GPU.

**Comment by cshopping** [comment] 2021-04-16 06:31
first of all; thank you very much.
i have try the new branch; it not work for me; i will check it further too.

**Comment by lshug** [comment] 2021-04-16 15:56
My bad, looks like a some bad argument handling snuck into build.py. I've pushed a fix. Can you try again?

**Comment by cshopping** [comment] 2021-04-17 10:47
I have made the modification you submitted during the test, otherwise the test cannot be performed. This is a small problem; the problem now is： Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic -sized tensors

**Comment by lshug** [comment] 2021-04-20 02:12
Is it still appearing in all three modules, or is process_kp_driving fine now? Fingers crossed it's the latter.

**Comment by lshug** [comment] 2021-05-04 22:27
I'm closing the issue due to inactivity. That said, I'm working on adding GPU delegate support.

**Closed as completed by lshug** 2021-05-04 22:27 UTC
